Repository CodeSystem2022/e-commerce-los-borbocoders, pull requests merged in 2023-11, with the labels that each got.

#43 Order class
  backend/src/models/Order.py
Labels: development

#46 index.html
  frontend/images/1_.png
  frontend/images/2_.png
  frontend/images/3_.png
  frontend/images/Thumbs.db
  frontend/images/car.svg
  frontend/images/f1_.png
  frontend/images/f2_.png
  frontend/images/f3_.png
  frontend/images/i1.svg
  frontend/images/i2.svg
  frontend/images/i3.svg
  frontend/images/menu.png
  frontend/images/tecnofer.png
  frontend/src/index.html
Labels: development

#48 order class update
  backend/src/models/Order.py
  backend/src/models/order.py
Labels: enhancement

#51 update utils/decimal_ecoder - product.py
  backend/src/models/Product.py
  backend/src/services/product_service.py
  backend/src/utils/decimal_ecoder.py
Labels: development

#52 Agregado de favicon
  frontend/images/favicon.png
Labels: enhancement

#53 Update index.html
  frontend/src/index.html
Labels: enhancement

#50 App Class
  backend/src/app.py
Labels: development

#67 Cart Class
  backend/src/models/cart.py
Labels: development

#69 Update payment-success.html
  frontend/src/templates/payment-success.html
Labels: development

#70 Update payment-success.css
  frontend/src/css/payment-success.css
Labels: development

#74 Request Handler Service
  backend/src/services/request_handler_service.py
Labels: development

#77 Order Service
  backend/src/services/order_service.py
Labels: development

#71 Update and rename index.js to main.js
  frontend/src/js/index.js
  frontend/src/js/main.js
Labels: enhancement

#78 mercadopago Service
  backend/src/services/mercadopago_service.py
Labels: development

#79 Request Parser
  backend/src/utils/RequestParser.py
Labels: development

#80 Headers Setter
  backend/src/utils/set_headers.py
Labels: development

#73 se agrego el mp a mercado.js
  frontend/src/js/services/mercadopago.js
Labels: development

#76 modificando el index.html
  frontend/src/index.html
Labels: development

#83 Update payment-error.html
  frontend/src/templates/payment-error.html
Labels: development

#89 Update products.js
  frontend/src/js/products.js
Labels: development

#107 Validations update, and modularization improvements.
  frontend/src/js/services/checkout.js
Labels: enhancement, development

#108 Validations Finished.
  frontend/src/js/services/validations.js
Labels: enhancement, development

#110 Fixing small details & typos
  backend/src/app.py
  backend/src/database/database.py
  backend/src/models/Product.py
  backend/src/models/cart.py
  backend/src/models/customer.py
  backend/src/models/product.py
  backend/src/services/mercadopago_service.py
  backend/src/services/order_service.py
  backend/src/services/request_handler_service.py
  backend/src/services/user_service.py
  backend/src/utils/request_parser.py
  backend/src/utils/set_headers.py
Labels: bug, enhancement
